Improve came scripts to check if the config exists

diff --git a/bin/came-exec b/bin/came-exec
--- a/bin/came-exec
+++ b/bin/came-exec
@@ -1,4 +1,9 @@
 #!/bin/bash
+if [[ ! -e ~/.config/came.conf ]]; then
+    echo "came config file not found"
+    echo "run came-setup first"
+    exit 1
+fi
 source ~/.config/came.conf
 
 distrobox enter $dcid -- "$@"
